spring.application.name=config-service
server.port=8888

# Mode native = fichiers servis depuis le classpath (dossier /config)
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
